### ISSUE TITLE
Impossible d'ouvrir la page de données personnelles

### ISSUE THREAD

**Issue by daniel-ob** [abouchereau/easyamap#17]
Bonjour,

Je vous fais part d'une erreur que je rencontre en tant qu'utilisateur quand j'essaie d'accéder à la page de données personnelles.

Étant connecté, dans la page d’accueil https://amapoberry.easyamap.fr/ quand je clique sur mon nom d'utilisateur dans le menu de navigation, j'obtiens l'erreur 500 suivante:

![image](https://user-images.githubusercontent.com/9929452/187280874-827d10d6-5770-4ba4-abf9-93dd9d6fc061.png)

Je reste à votre disposition pour tout renseignement complémentaire.

Cordialement,
Daniel

**Comment by abouchereau** [comment]
C'est corrigé.
Merci d'avoir remonté le problème

**Comment by abouchereau** [comment]
C'est corrigé.
Merci d'avoir remonté le problème

**Comment by daniel-ob** [comment]
Merci pour la correction. Je confirme que je peux bien accéder à la page de données personnelles maintenant.
